import { ReactNode } from "react";
import { AlertTriangle } from "lucide-react";

interface Props {
  title: string;
  description: string;
  icon: ReactNode;
  children: ReactNode;
}

export function AIToolShell({ title, description, icon, children }: Props) {
  return (
    <div className="mx-auto max-w-5xl space-y-6 p-6 md:p-10">
      <div className="flex items-start gap-4">
        <div
          className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl text-primary-foreground"
          style={{ background: "var(--gradient-primary)" }}
        >
          {icon}
        </div>
        <div>
          <h1 className="text-2xl font-bold tracking-tight md:text-3xl">{title}</h1>
          <p className="mt-1 text-sm text-muted-foreground md:text-base">{description}</p>
        </div>
      </div>

      {children}

      <div className="flex items-start gap-2 rounded-lg border border-border bg-muted/40 p-3 text-xs text-muted-foreground">
        <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
        <p>
          <span className="font-medium text-foreground">Responsible AI:</span> Outputs are generated by AI and may
          contain inaccuracies, bias, or fabricated details. Always review and edit before sharing externally or
          relying on the content for decisions.
        </p>
      </div>
    </div>
  );
}
